
publish_mode: editorial_workflow
media_folder: "uploads/versions" # Media files will be stored in the repo under uploads/versions

backend:
  name: git-gateway
  repo: https://github.com/aerolp/netlify-insignia-capital-teste3
  branch: devlp # Branch to update (optional; defaults to master)
  site_domain: biologist-badger-47215.netlify.com

collections:
  - name: "equipa"
    label: "Equipa"
    folder: "_posts/equipa"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout" , widget: "hidden", default: "post" }
      - { label: "Titulo", name: "titulo", widget: "string" }
      - {label: "Data de publicação", name: "date", widget: "datetime"}
      - { label: "Class", name: "classe", widget: "hidden", default: "Trabalhador" }  
      - { label: "Categoria", name: "category", widget: "select", options: [ "executivo" , "analista" , "consultivo"] }
      - { label: "Nome da Imagem", name: "nome-imagem", widget: "string" }
  - name: "portfolios"
    label: "Portfolios"
    folder: "_posts/portfolios"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titulo", name: "titulo", widget: "string" }
      - { label: "Class", name: "classe", widget: "hidden", default: "Trabalhador" }
      - { label: "imagem de Esterior", name: "fora_image_path", widget: "image" }
      - { label: "imagem de interior", name: "dentro_image_path", widget: "image" }
      - { label: "Categoria", name: "category", widget: "hidden", default: "portfolios" }
      - { label: "Nome da Imagem", name: "nome-imagem", widget: "string" }
      - { label: "Website", name: "website", widget: "string" }
      - { label: "Sector", name: "sector", widget: "string" }
      - { label: "Tipo de Operacoes", name: "tipo-de-operacao", widget: "string" }
      - { label: "Ano", name: "data", widget: "string" }
      - { label: "Vendas", name: "vendas", widget: "string" }
      - { label: "CEO", name: "CEO", widget: "string" }
      - { label: "Descricao", name: "descricao", widget: "string" }
  - name: "data"
    label: "Data"
    editor:
      preview: true
    files:
      - name: "footer-pages"
        label: "FAQ"
        file: "_data/footer-pages.yml"
        description: FAQ questions 
        fields:
          - label: "faq"
            name: faq
            widget: "object"
            fields:
              - label: "sobre"
                name: sobre
                widget: "list"
                fields:
                  - { label: "Pergunta", name: "pergunta", widget: "string" }
                  - { label: "Resposta", name: "resposta", widget: "string" }





