
publish_mode: editorial_workflow
media_folder: "uploads" # Media files will be stored in the repo under images/uploads

backend:
  name: git-gateway
  branch: devlp # Branch to update (optional; defaults to master)
  site_domain: biologist-badger-47215.netlify.com

collections:
  - name: "equipa"
    label: "Equipa"
    folder: "_posts/equipa"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout" , widget: "hidden", default: "post" }
      - { label: "Title", name: "titulo", widget: "string" }
      - { label: "Class", name: "classe", widget: "hidden", default: "Trabalhador" }
      - { label: "Feature image", name: "background_image_path", widget: "image" }
      - { label: "Category", name: "category", widget: "category" }
      - { label: "Description", name: "nome-imagem", widget: "string" }
      - { label: "Description", name: "cargo", widget: "string" }
      - { label: "Description", name: "email", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "portfolios"
    label: "Portfolios"
    folder: "_posts/portfolios"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "titulo", widget: "string" }
      - { label: "Class", name: "classe", widget: "hidden", default: "Trabalhador" }
      - { label: "Feature image", name: "fora_image_path", widget: "image" }
      - { label: "Feature image", name: "dentro_image_path", widget: "image" }
      - { label: "Category", name: "category", widget: "category" }
      - { label: "Description", name: "nome-imagem", widget: "string" }
      - { label: "Description", name: "website", widget: "string" }
      - { label: "Description", name: "sector", widget: "string" }
      - { label: "Description", name: "tipo-de-operacao", widget: "string" }
      - { label: "Description", name: "data", widget: "string" }
      - { label: "Description", name: "vendas", widget: "string" }
      - { label: "Description", name: "CEO", widget: "string" }
      - { label: "Description", name: "descricao", widget: "string" }



